version: 2.1

executors:
  normal_container:
    docker:
      - image: cimg/node:lts

jobs:
  unit-test:
    executor: normal_container
    steps:
      - checkout
      - run:
          name: unit-test
          command: |
            echo "run unit-test"

            if ./change_codeowners_only.sh; then
                echo "This job is skipped because only CODEOWNERS file was changed."
                circleci-agent step halt
            fi

            echo "Running unit tests..."


  deploy:
    executor: normal_container
    steps:
      - run:
          name: deploy
          command: |
            echo "run deploy"

            if ./change_codeowners_only.sh; then
                echo "This job is skipped because only CODEOWNERS file was changed."
                circleci-agent step halt
            fi

            echo "Running deployment..."

workflows:
  release:
    jobs:
      - unit-test
      - deploy:
          requires:
            - unit-test

